# Generated by Django 5.2.1 on 2025-05-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(default='Title', max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='full_text',
            field=models.TextField(verbose_name='Обратная связь'),
        ),
    ]
